"""remove uniqu from tabl

Revision ID: 04780b614a05
Revises: ff7ba35906c6
Create Date: 2024-10-04 16:22:26.156708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04780b614a05'
down_revision: Union[str, None] = 'ff7ba35906c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('player_game_info_game_key', 'player_game_info', type_='unique')
    op.alter_column('teams', 'teamCode',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teams', 'teamCode',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint('player_game_info_game_key', 'player_game_info', ['game'])
    # ### end Alembic commands ###
