"""Create data match player

Revision ID: 0b5cad5e25a0
Revises: 98ed71a19c71
Create Date: 2024-10-16 22:54:38.540975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b5cad5e25a0'
down_revision: Union[str, None] = '98ed71a19c71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bgmi_matches_tournament_id_fkey', 'bgmi_matches', type_='foreignkey')
    op.drop_column('bgmi_matches', 'tournament_id')
    op.add_column('match_players', sa.Column('player_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'match_players', 'players', ['player_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'match_players', type_='foreignkey')
    op.drop_column('match_players', 'player_id')
    op.add_column('bgmi_matches', sa.Column('tournament_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('bgmi_matches_tournament_id_fkey', 'bgmi_matches', 'tournaments', ['tournament_id'], ['id'])
    # ### end Alembic commands ###
