"""Created player column

Revision ID: 29ab1fe2c5ae
Revises: e2f8b689503d
Create Date: 2024-10-04 14:41:25.139029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29ab1fe2c5ae'
down_revision: Union[str, None] = 'e2f8b689503d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('logged_in', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'logged_in')
    # ### end Alembic commands ###
