"""Added column

Revision ID: 3103e3f569af
Revises: ee4ee5d7bbae
Create Date: 2024-07-28 11:00:17.805501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3103e3f569af'
down_revision: Union[str, None] = 'ee4ee5d7bbae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_players', sa.Column('dead_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match_players', 'dead_at')
    # ### end Alembic commands ###
