"""change in player table

Revision ID: 6665c3557ba6
Revises: f097f8fafd80
Create Date: 2024-07-17 22:53:57.462249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6665c3557ba6'
down_revision: Union[str, None] = 'f097f8fafd80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bgmi_players', sa.Column('verified', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bgmi_players', 'verified')
    # ### end Alembic commands ###
