"""Added martch table

Revision ID: 6720f76bcc4e
Revises: cb749b23aa24
Create Date: 2024-07-17 22:17:05.433622

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6720f76bcc4e"
down_revision: Union[str, None] = "cb749b23aa24"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bgmi_matches",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tournament_id", sa.UUID(), nullable=True),
        sa.Column("match_name", sa.Integer(), nullable=True),
        sa.Column("match_type", sa.String(), nullable=True),
        sa.Column("map", sa.String(), nullable=True),
        sa.Column("mode", sa.String(), nullable=True),
        sa.Column("match_date", sa.DateTime(), nullable=True),
        sa.Column("match_status", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["tournament_id"],
            ["tournaments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bgmi_matches_id"), "bgmi_matches", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_bgmi_matches_id"), table_name="bgmi_matches")
    op.drop_table("bgmi_matches")
    # ### end Alembic commands ###
