"""added enroll field

Revision ID: 775d1b9406d1
Revises: 6665c3557ba6
Create Date: 2024-07-18 15:13:39.736472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '775d1b9406d1'
down_revision: Union[str, None] = '6665c3557ba6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bgmi_players', sa.Column('enrollNo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bgmi_players', 'enrollNo')
    # ### end Alembic commands ###
