"""Created submited button

Revision ID: 98ed71a19c71
Revises: d8b1f37e7338
Create Date: 2024-10-04 19:36:56.585777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98ed71a19c71'
down_revision: Union[str, None] = 'd8b1f37e7338'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('submitted', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'submitted')
    # ### end Alembic commands ###
