"""Added 

Revision ID: b7a0e0778726
Revises: effa6f2a9812
Create Date: 2024-07-17 21:18:16.296211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7a0e0778726'
down_revision: Union[str, None] = 'effa6f2a9812'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_teams_teamName', table_name='teams')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_teams_teamName', 'teams', ['teamName'], unique=True)
    # ### end Alembic commands ###
