"""change in tournament table

Revision ID: cb749b23aa24
Revises: b7a0e0778726
Create Date: 2024-07-17 21:42:32.605407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb749b23aa24'
down_revision: Union[str, None] = 'b7a0e0778726'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('team_type', sa.String(), nullable=True))
    op.add_column('tournaments', sa.Column('city', sa.String(), nullable=True))
    op.add_column('tournaments', sa.Column('max_teams', sa.Integer(), nullable=True))
    op.add_column('tournaments', sa.Column('pool_prize', sa.Integer(), nullable=True))
    op.add_column('tournaments', sa.Column('org_name', sa.String(), nullable=True))
    op.add_column('tournaments', sa.Column('tournament_logo', sa.String(), nullable=True))
    op.drop_column('tournaments', 'mode')
    op.drop_column('tournaments', 'total_players')
    op.drop_column('tournaments', 'type')
    op.drop_column('tournaments', 'first_prize')
    op.drop_column('tournaments', 'map')
    op.drop_column('tournaments', 'total_teams')
    op.drop_column('tournaments', 'third_prize')
    op.drop_column('tournaments', 'second_prize')
    op.drop_column('tournaments', 'end_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('tournaments', sa.Column('second_prize', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tournaments', sa.Column('third_prize', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tournaments', sa.Column('total_teams', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tournaments', sa.Column('map', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tournaments', sa.Column('first_prize', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tournaments', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tournaments', sa.Column('total_players', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tournaments', sa.Column('mode', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('tournaments', 'tournament_logo')
    op.drop_column('tournaments', 'org_name')
    op.drop_column('tournaments', 'pool_prize')
    op.drop_column('tournaments', 'max_teams')
    op.drop_column('tournaments', 'city')
    op.drop_column('tournaments', 'team_type')
    # ### end Alembic commands ###
