"""Changes in team table

Revision ID: e2f8b689503d
Revises: b3b59c086d32
Create Date: 2024-10-04 13:49:59.627299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e2f8b689503d'
down_revision: Union[str, None] = 'b3b59c086d32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('player_name', sa.String(), nullable=True),
    sa.Column('mobile', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('college', sa.String(), nullable=True),
    sa.Column('discord', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('mobile')
    )
    op.create_index(op.f('ix_players_id'), 'players', ['id'], unique=False)
    op.create_table('player_game_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=True),
    sa.Column('game', sa.String(), nullable=True),
    sa.Column('game_id', sa.String(), nullable=True),
    sa.Column('game_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game'),
    sa.UniqueConstraint('game_id'),
    sa.UniqueConstraint('game_name')
    )
    op.create_index(op.f('ix_player_game_info_id'), 'player_game_info', ['id'], unique=False)
    # op.drop_index('ix_bgmi_players_id', table_name='bgmi_players')
    # op.drop_table('bgmi_players')
    # op.drop_constraint('bgmi_matches_mvp_player_id_fkey', 'bgmi_matches', type_='foreignkey')
    op.drop_column('bgmi_matches', 'mvp_player_id')
    # op.drop_constraint('match_players_player_id_fkey', 'match_players', type_='foreignkey')
    op.drop_column('match_players', 'player_id')
    op.add_column('organizations', sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=True))
    op.add_column('organizations', sa.Column('password', sa.String(), nullable=True))
    op.drop_column('organizations', 'hashed_password')
    op.drop_column('organizations', 'disabled')
    op.add_column('teams', sa.Column('tramCode', sa.String(), nullable=True))
    op.drop_constraint('teams_tournament_id_fkey', 'teams', type_='foreignkey')
    op.drop_column('teams', 'tournament_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('tournament_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('teams_tournament_id_fkey', 'teams', 'tournaments', ['tournament_id'], ['id'])
    op.drop_column('teams', 'tramCode')
    op.add_column('organizations', sa.Column('disabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('organizations', 'password')
    op.drop_column('organizations', 'active')
    op.add_column('match_players', sa.Column('player_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('match_players_player_id_fkey', 'match_players', 'bgmi_players', ['player_id'], ['id'])
    op.add_column('bgmi_matches', sa.Column('mvp_player_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('bgmi_matches_mvp_player_id_fkey', 'bgmi_matches', 'bgmi_players', ['mvp_player_id'], ['id'])
    op.create_table('bgmi_players',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tournament_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('team_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('player_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('game_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('captain', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('mobile', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('college', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_joined', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('kill', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_dead', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('enrollNo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name='bgmi_players_team_id_fkey'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], name='bgmi_players_tournament_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='bgmi_players_pkey')
    )
    op.create_index('ix_bgmi_players_id', 'bgmi_players', ['id'], unique=False)
    op.drop_index(op.f('ix_player_game_info_id'), table_name='player_game_info')
    op.drop_table('player_game_info')
    op.drop_index(op.f('ix_players_id'), table_name='players')
    op.drop_table('players')
    # ### end Alembic commands ###
