"""added enrollment no in table

Revision ID: ea0935b6203a
Revises: 04780b614a05
Create Date: 2024-10-04 16:25:55.936097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea0935b6203a'
down_revision: Union[str, None] = '04780b614a05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('enrollment_no', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'players', ['enrollment_no'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'players', type_='unique')
    op.drop_column('players', 'enrollment_no')
    # ### end Alembic commands ###
