"""addede tabvle

Revision ID: ee4ee5d7bbae
Revises: 775d1b9406d1
Create Date: 2024-07-20 12:28:51.700320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee4ee5d7bbae'
down_revision: Union[str, None] = '775d1b9406d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_players',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=True),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('player_id', sa.UUID(), nullable=True),
    sa.Column('is_joined', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('kill', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('rank', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('is_dead', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['bgmi_matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['bgmi_players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_players_id'), 'match_players', ['id'], unique=False)
    op.add_column('bgmi_matches', sa.Column('mvp_player_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'bgmi_matches', 'bgmi_players', ['mvp_player_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bgmi_matches', type_='foreignkey')
    op.drop_column('bgmi_matches', 'mvp_player_id')
    op.drop_index(op.f('ix_match_players_id'), table_name='match_players')
    op.drop_table('match_players')
    # ### end Alembic commands ###
