"""Created player column

Revision ID: ff7ba35906c6
Revises: 29ab1fe2c5ae
Create Date: 2024-10-04 14:44:08.261660

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ff7ba35906c6"
down_revision: Union[str, None] = "29ab1fe2c5ae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "teams", sa.Column("teamCode", sa.String(), nullable=False, unique=True)
    )
    op.drop_column("teams", "tramCode")
    op.add_column("players", sa.Column("team_code", sa.String(), nullable=True))
    op.create_foreign_key(None, "players", "teams", ["team_code"], ["teamCode"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "teams", sa.Column("tramCode", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_column("teams", "teamCode")
    op.drop_constraint(None, "players", type_="foreignkey")
    op.drop_column("players", "team_code")
    # ### end Alembic commands ###
